title: Boyi Xiao's Homepage
page-top-title: Boyi Xiao
top-section-bg-text: Be what you wanna be
home-subtitle: Boyi Xiao&ensp;|&ensp;Personal Website
copyright-text: '&copy; Boyi Xiao 2023-2025. All Rights Reserved.'
